runtime: aspnetcore
env: flex
entrypoint: ./YourWebApiProjectName

env_variables:
  ASPNETCORE_ENVIRONMENT: "Production"
  # Add any other environment variables your application needs

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
