name: Deploy to Google Cloud

on:
  push:
    branches:
      - Dev  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release

      - name: Publish Application
        run: dotnet publish --configuration Release --output ./publish

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: neon-research-397309  # Replace with your Google Cloud Project ID

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy ./publish/app.yml --quiet
