name: 🚀 Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - Dev

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish --configuration Release --no-restore
      # Add any additional build steps as needed

  deploy:
    name: Deploy to AWS Elastic Beanstalk
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS Elastic Beanstalk
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAZWBFJTF3Q3NSIP6L
          aws-secret-access-key: 95iVpwyzyFKJrOkisyq/EP/HTw/Y6vlhRjwewNrx
          aws-region: us-east-1 # Change to your desired AWS region

      - name: Install EB CLI
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          sudo pip3 install awsebcli
          
      - name: Initialize Elastic Beanstalk
        run: eb init -p 'your-platform-name' -r us-east-1
        # Replace 'your-platform-name' and 'us-east-1' with your specific values

      - name: Deploy to Elastic Beanstalk
        run: eb deploy your-environment-name
        # Replace 'your-environment-name' with your specific environment name

      - name: Deploy status
        run: eb status

# Optionally, you can add more jobs for testing, approval, etc., as needed.
