name: Deploy to Heroku

on:
  push:
    branches:
      - Dev

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish --configuration Release --no-restore

  deploy:
    name: Deploy to Heroku
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku
        run: heroku login -i

      - name: Deploy to Heroku
        run: heroku deploy newbullseye
        # Replace 'your-app-name' with your Heroku app name
