name: Deploy to Heroku
on:
  push:
    branches:
      - Dev

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish --configuration Release --no-restore
      # Add any additional build steps as needed

  deploy:
    name: Deploy to Heroku
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Heroku
        uses: heroku/setup-heroku@v1

      - name: Deploy to Heroku
        run: heroku deploy bullsmart
        # Replace 'your-app-name' with your Heroku app name
